# Generated by Django 4.2.4 on 2023-10-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="comentarios",
            name="ranking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="general.rating"
            ),
        ),
    ]
