# Generated by Django 4.2.4 on 2023-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_rating_alter_comentarios_ranking"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rating",
            new_name="Review",
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Catalogo",
                "verbose_name_plural": "Catalogos",
            },
        ),
        migrations.AddField(
            model_name="categoria",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
