# Generated by Django 4.2.4 on 2023-10-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0005_remove_categoria_featured_remove_categoria_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="descripcion",
            field=models.TextField(null=True),
        ),
    ]
